/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FileId = IDL.Text;
export const FolderId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Timestamp = IDL.Int;
export const MediaFile = IDL.Record({
  'id' : FileId,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'size' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'mimeType' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'isPublic' : IDL.Bool,
  'folderId' : IDL.Opt(FolderId),
});
export const MediaFolder = IDL.Record({
  'id' : FolderId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'parentId' : IDL.Opt(FolderId),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFileRecord' : IDL.Func(
      [
        FileId,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(FolderId),
        IDL.Vec(IDL.Text),
        ExternalBlob,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'createFolder' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'deleteFile' : IDL.Func([FileId], [], []),
  'deleteFolder' : IDL.Func([IDL.Text], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFileById' : IDL.Func([FileId], [IDL.Opt(MediaFile)], ['query']),
  'getFilesByFolder' : IDL.Func([IDL.Text], [IDL.Vec(MediaFile)], ['query']),
  'getFilesByMimeType' : IDL.Func([IDL.Text], [IDL.Vec(MediaFile)], ['query']),
  'getFolderById' : IDL.Func([IDL.Text], [IDL.Opt(MediaFolder)], ['query']),
  'getPublicFiles' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllFiles' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
  'listAllFolders' : IDL.Func([], [IDL.Vec(MediaFolder)], ['query']),
  'moveFileToFolder' : IDL.Func([FileId, IDL.Opt(FolderId)], [], []),
  'renameFile' : IDL.Func([FileId, IDL.Text], [], []),
  'renameFolder' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'searchFilesByTag' : IDL.Func([IDL.Text], [IDL.Vec(MediaFile)], ['query']),
  'toggleFilePublic' : IDL.Func([FileId], [], []),
  'updateFileTags' : IDL.Func([FileId, IDL.Vec(IDL.Text)], [], []),
  'forceClaimAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FileId = IDL.Text;
  const FolderId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Timestamp = IDL.Int;
  const MediaFile = IDL.Record({
    'id' : FileId,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'size' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'mimeType' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'isPublic' : IDL.Bool,
    'folderId' : IDL.Opt(FolderId),
  });
  const MediaFolder = IDL.Record({
    'id' : FolderId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'parentId' : IDL.Opt(FolderId),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFileRecord' : IDL.Func(
        [
          FileId,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(FolderId),
          IDL.Vec(IDL.Text),
          ExternalBlob,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'createFolder' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'deleteFile' : IDL.Func([FileId], [], []),
    'deleteFolder' : IDL.Func([IDL.Text], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFileById' : IDL.Func([FileId], [IDL.Opt(MediaFile)], ['query']),
    'getFilesByFolder' : IDL.Func([IDL.Text], [IDL.Vec(MediaFile)], ['query']),
    'getFilesByMimeType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MediaFile)],
        ['query'],
      ),
    'getFolderById' : IDL.Func([IDL.Text], [IDL.Opt(MediaFolder)], ['query']),
    'getPublicFiles' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllFiles' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
    'listAllFolders' : IDL.Func([], [IDL.Vec(MediaFolder)], ['query']),
    'moveFileToFolder' : IDL.Func([FileId, IDL.Opt(FolderId)], [], []),
    'renameFile' : IDL.Func([FileId, IDL.Text], [], []),
    'renameFolder' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'searchFilesByTag' : IDL.Func([IDL.Text], [IDL.Vec(MediaFile)], ['query']),
    'toggleFilePublic' : IDL.Func([FileId], [], []),
    'updateFileTags' : IDL.Func([FileId, IDL.Vec(IDL.Text)], [], []),
    'forceClaimAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };