/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type FileId = string;
export type FolderId = string;
export interface MediaFile {
  'id' : FileId,
  'blob' : ExternalBlob,
  'name' : string,
  'createdAt' : Timestamp,
  'size' : bigint,
  'tags' : Array<string>,
  'mimeType' : string,
  'description' : [] | [string],
  'isPublic' : boolean,
  'folderId' : [] | [FolderId],
}
export interface MediaFolder {
  'id' : FolderId,
  'name' : string,
  'createdAt' : Timestamp,
  'parentId' : [] | [FolderId],
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFileRecord' : ActorMethod<
    [
      FileId,
      string,
      bigint,
      string,
      [] | [FolderId],
      Array<string>,
      ExternalBlob,
      [] | [string],
    ],
    undefined
  >,
  'createFolder' : ActorMethod<[string, string, [] | [string]], undefined>,
  'deleteFile' : ActorMethod<[FileId], undefined>,
  'deleteFolder' : ActorMethod<[string], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileById' : ActorMethod<[FileId], [] | [MediaFile]>,
  'getFilesByFolder' : ActorMethod<[string], Array<MediaFile>>,
  'getFilesByMimeType' : ActorMethod<[string], Array<MediaFile>>,
  'getFolderById' : ActorMethod<[string], [] | [MediaFolder]>,
  'getPublicFiles' : ActorMethod<[], Array<MediaFile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllFiles' : ActorMethod<[], Array<MediaFile>>,
  'listAllFolders' : ActorMethod<[], Array<MediaFolder>>,
  'moveFileToFolder' : ActorMethod<[FileId, [] | [FolderId]], undefined>,
  'renameFile' : ActorMethod<[FileId, string], undefined>,
  'renameFolder' : ActorMethod<[string, string], undefined>,
  'searchFilesByTag' : ActorMethod<[string], Array<MediaFile>>,
  'toggleFilePublic' : ActorMethod<[FileId], undefined>,
  'updateFileTags' : ActorMethod<[FileId, Array<string>], undefined>,
  'forceClaimAdmin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];